app:
  http_port: 9999
  http_addr: "0.0.0.0"
  grpc_port: 8888
  grpc_addr: "0.0.0.0"
  language: zh
  max_header_size: 1 # 单位 m
  read_timeout: 60 # 单位 s
  read_header_timeout: 60 # 单位 s
  write_timeout: 60 # 单位 s
  tls: false # true | false
  cert_file: "config/www.ikubeops.local_chain.crt"
  key_file: "config/www.ikubeops.local_key.key"
  shutdown_timeout: 60

cli:
  demo: "demo in config"

logger:
  output: "console" # console | file
  format: "console" # json | console
  level: "debug" # debug | info | warn | error
  dev: true # true | false
  file_path: "logs/" #
  max_size: 10 # 单位 m
  max_age: 30
  max_backups: 10
